/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BLL.CategoryBLL;
import Custom.TableActionCellEditor;
import Custom.TableActionCellRender;
import Custom.TableActionEvent;
import GUI.dialog.DanhMucDialog;
import POJO.Category;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import static javax.swing.GroupLayout.Alignment.CENTER;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class DanhMucGUI extends javax.swing.JPanel {
    private CategoryBLL cateBLL;
    
    private List<Category> listCate = new ArrayList<>();
    
    DanhMucDialog d;
    
    
    /**
     * Creates new form DanhMucGUI
     */
    public DanhMucGUI() {
        initComponents();

        cateBLL = new CategoryBLL();
        
        loadCategoryTable();
        
        d = new DanhMucDialog(this);
    }

    public void ActionTable(){
        TableActionEvent event = new TableActionEvent() {
            @Override
            public void onEdit(int row) {
                d.status=0;
                d.setCategory(listCate.get(row));
                d.setVisible(true);
            }

            @Override
            public void onDelete(int row) {
                if (table.isEditing()) {
                    table.getCellEditor().stopCellEditing();
                     if(table.getSelectionModel().isSelectionEmpty() == true)
                        JOptionPane.showMessageDialog(null, "Vui lòng chọn loại sản phẩm muốn xóa");
                    else{
                        int confirm =JOptionPane.showConfirmDialog(null,"Bạn có chắc chắn muốn xóa sản phẩm này?","Xác nhận",JOptionPane.YES_NO_OPTION);
                        if(confirm==JOptionPane.YES_OPTION){
                            Category c = cateBLL.getCategory(listCate.get(row).getCategoryID());
//                            c.setCategoryID(listCate.get(row).getCategoryID());
//                            c.setName(listCate.get(row).getName());
//                            c.setDescription(listCate.get(row).getDescription());
                            cateBLL.deleteCategory(c);
                            DefaultTableModel model = (DefaultTableModel) table.getModel();
                            model.removeRow(row);
                        }
                        }
                }
               
            }

            @Override
            public void onView(int row) {
                System.out.println("View row : " + row);
            }

            @Override
            public void choice(int row) {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }

            @Override
            public void add(int row) {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }

            @Override
            public void minus(int row) {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }

            
        };
        table.getColumnModel().getColumn(4).setCellRenderer(new TableActionCellRender());
        table.getColumnModel().getColumn(4).setCellEditor(new TableActionCellEditor(event));
    }
    
    public void loadCategoryTable(){
        listCate = cateBLL.loadCategory();
        Object[][] datamodel;
        datamodel = cateBLL.convertList(listCate);
        String[] title={"TT","Name","Description","Count of Vegetable","Action"};
        DefaultTableModel model = new DefaultTableModel(datamodel,title);
        table.setModel(model);
        ActionTable();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRadius3 = new Custom.PanelRadius();
        jLabel1 = new javax.swing.JLabel();
        panelRadius1 = new Custom.PanelRadius();
        txt_Category = new javax.swing.JTextField();
        btn_Search = new Custom.ButtonRadius();
        btn_Add = new Custom.ButtonRadius();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new Custom.TableCustom1();
        jLabel10 = new javax.swing.JLabel();
        buttonRadius2 = new Custom.ButtonRadius();

        panelRadius3.setBackground(new java.awt.Color(63, 86, 185));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Danh mục sản phẩm");

        javax.swing.GroupLayout panelRadius3Layout = new javax.swing.GroupLayout(panelRadius3);
        panelRadius3.setLayout(panelRadius3Layout);
        panelRadius3Layout.setHorizontalGroup(
            panelRadius3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRadius3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(986, Short.MAX_VALUE))
        );
        panelRadius3Layout.setVerticalGroup(
            panelRadius3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRadius3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelRadius1.setBackground(new java.awt.Color(255, 255, 255));
        panelRadius1.setForeground(new java.awt.Color(255, 255, 255));
        panelRadius1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        panelRadius1.setRoundBottomLeft(20);
        panelRadius1.setRoundBottomRight(20);
        panelRadius1.setRoundTopLeft(20);
        panelRadius1.setRoundTopRight(20);

        txt_Category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CategoryActionPerformed(evt);
            }
        });

        btn_Search.setBackground(new java.awt.Color(153, 255, 0));
        btn_Search.setForeground(new java.awt.Color(255, 255, 255));
        btn_Search.setText("TÌm kiếm");
        btn_Search.setColor(new java.awt.Color(153, 255, 0));
        btn_Search.setColorClick(new java.awt.Color(51, 153, 0));
        btn_Search.setColorOver(new java.awt.Color(0, 204, 51));
        btn_Search.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Search.setRoundBottomLeft(6);
        btn_Search.setRoundBottomRight(6);
        btn_Search.setRoundTopLeft(6);
        btn_Search.setRoundTopRight(6);
        btn_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SearchActionPerformed(evt);
            }
        });

        btn_Add.setBackground(new java.awt.Color(255, 51, 51));
        btn_Add.setForeground(new java.awt.Color(255, 255, 255));
        btn_Add.setColor(new java.awt.Color(255, 51, 51));
        btn_Add.setColorClick(new java.awt.Color(153, 0, 0));
        btn_Add.setColorOver(new java.awt.Color(204, 0, 0));
        btn_Add.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Add.setLabel("Thêm mới");
        btn_Add.setRoundBottomLeft(6);
        btn_Add.setRoundBottomRight(6);
        btn_Add.setRoundTopLeft(6);
        btn_Add.setRoundTopRight(6);
        btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        table.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        table.setSelectionBackground(new java.awt.Color(54, 175, 106));
        jScrollPane2.setViewportView(table);

        jLabel10.setText("Loại sản phẩm");

        buttonRadius2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reload.png"))); // NOI18N
        buttonRadius2.setColor(new java.awt.Color(224, 224, 224));
        buttonRadius2.setColorClick(new java.awt.Color(153, 153, 153));
        buttonRadius2.setColorOver(new java.awt.Color(204, 204, 204));
        buttonRadius2.setRoundBottomLeft(5);
        buttonRadius2.setRoundBottomRight(5);
        buttonRadius2.setRoundTopLeft(5);
        buttonRadius2.setRoundTopRight(5);
        buttonRadius2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRadius2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRadius1Layout = new javax.swing.GroupLayout(panelRadius1);
        panelRadius1.setLayout(panelRadius1Layout);
        panelRadius1Layout.setHorizontalGroup(
            panelRadius1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRadius1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(panelRadius1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRadius1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRadius1Layout.createSequentialGroup()
                        .addGroup(panelRadius1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelRadius1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(buttonRadius2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1027, Short.MAX_VALUE)
                            .addGroup(panelRadius1Layout.createSequentialGroup()
                                .addComponent(txt_Category, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(64, 64, 64))))
        );
        panelRadius1Layout.setVerticalGroup(
            panelRadius1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRadius1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(panelRadius1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Category, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(buttonRadius2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRadius3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(panelRadius1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelRadius3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(panelRadius1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_CategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CategoryActionPerformed

    private void btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddActionPerformed
        // TODO add your handling code here:
//        d.setSize(new Dimension(400,370));
        d.setVisible(true);
        
    }//GEN-LAST:event_btn_AddActionPerformed

    private void btn_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SearchActionPerformed
        String str = txt_Category.getText();
        Object[][] datamodel;
        datamodel = cateBLL.convertList(cateBLL.searchCategory(str));
        String[] title={"TT","Name","Description","Count of Vegetable","Action"};
        DefaultTableModel model = new DefaultTableModel(datamodel,title);
        table.setModel(model);
        ActionTable();
    }//GEN-LAST:event_btn_SearchActionPerformed

    private void buttonRadius2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRadius2ActionPerformed
        // TODO add your handling code here:
        loadCategoryTable();
        txt_Category.setText("");
    }//GEN-LAST:event_buttonRadius2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Custom.ButtonRadius btn_Add;
    private Custom.ButtonRadius btn_Search;
    private Custom.ButtonRadius buttonRadius2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JScrollPane jScrollPane2;
    private Custom.PanelRadius panelRadius1;
    private Custom.PanelRadius panelRadius3;
    private Custom.TableCustom1 table;
    private javax.swing.JTextField txt_Category;
    // End of variables declaration//GEN-END:variables
}
