/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BLL.CustomersBLL;
import Custom.TableActionCellEditor;
import Custom.TableActionCellRender;
import Custom.TableActionEvent;
import GUI.dialog.KhachHangDialog;
import POJO.Customers;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class KhachHangGUI extends javax.swing.JPanel {
    private CustomersBLL cusBLL;
    private KhachHangDialog d;
    private List<Customers> listCustomer = new ArrayList<>();
    /**
     * Creates new form KhachHangGUI
     */
    public KhachHangGUI() {
        initComponents();
        
        cusBLL = new CustomersBLL();
        
        loadCustomers();
        
        d = new KhachHangDialog(this, listCustomer);
        
//        ActionTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void ActionTable(){
        TableActionEvent event = new TableActionEvent() {
            @Override
            public void onEdit(int row) {
                d.status=0;
                d.txt_IDCustomer.setText(listCustomer.get(row).getCustomerID()+"");
                d.lb_Customer.setText("Sửa thông tin khách hàng");
                d.txt_FullName.setText(listCustomer.get(row).getFullname());
                d.txt_Pass.setText(listCustomer.get(row).getPassword());
                d.txt_Adrress.setText(listCustomer.get(row).getAddress());
                d.txt_City.setText(listCustomer.get(row).getCity());
                d.setVisible(true);
            }

            @Override
            public void onDelete(int row) {
                if (table.isEditing()) {
                    table.getCellEditor().stopCellEditing();
                    if(table.getSelectionModel().isSelectionEmpty() == true)
                        JOptionPane.showMessageDialog(null, "Vui lòng chọn khách hàng muốn xóa");
                    else{
                        int confirm =JOptionPane.showConfirmDialog(null,"Bạn có chắc chắn muốn xóa sản phẩm này?","Xác nhận",JOptionPane.YES_NO_OPTION);
                        if(confirm==JOptionPane.YES_OPTION){
                            Customers c = new Customers();
                            c.setCustomerID(listCustomer.get(row).getCustomerID());
                            c.setFullname(listCustomer.get(row).getFullname());
                            c.setPassword(listCustomer.get(row).getPassword());
                            c.setAddress(listCustomer.get(row).getAddress());
                            c.setCity(listCustomer.get(row).getCity());
                            cusBLL.deleteCustomer(c);
                            DefaultTableModel model = (DefaultTableModel) table.getModel();
                            model.removeRow(row);
                        }
                    }
                }
            }

            @Override
            public void onView(int row) {
            }

            @Override
            public void choice(int row) {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }

            @Override
            public void add(int row) {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }

            @Override
            public void minus(int row) {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        };
        table.getColumnModel().getColumn(6).setCellRenderer(new TableActionCellRender());
        table.getColumnModel().getColumn(6).setCellEditor(new TableActionCellEditor(event));
    }
    public void loadCustomers(){
        listCustomer = cusBLL.loadCustomers();
        Object[][] datamodel;
        datamodel = cusBLL.convertList(listCustomer);
        String[] title={"ID","Password","FullName","Address","City","Count Order","Action"};
        DefaultTableModel model = new DefaultTableModel(datamodel,title);
        table.setModel(model);
        ActionTable();
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRadius9 = new Custom.PanelRadius();
        jLabel7 = new javax.swing.JLabel();
        panelRadius2 = new Custom.PanelRadius();
        txt_FullName = new javax.swing.JTextField();
        btn_Search = new Custom.ButtonRadius();
        btn_Add = new Custom.ButtonRadius();
        jScrollPane3 = new javax.swing.JScrollPane();
        table = new Custom.TableCustom1();
        txt_City = new javax.swing.JTextField();
        txt_Address = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        buttonRadius1 = new Custom.ButtonRadius();

        setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        panelRadius9.setBackground(new java.awt.Color(63, 86, 185));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Khách hàng");

        javax.swing.GroupLayout panelRadius9Layout = new javax.swing.GroupLayout(panelRadius9);
        panelRadius9.setLayout(panelRadius9Layout);
        panelRadius9Layout.setHorizontalGroup(
            panelRadius9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRadius9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(986, Short.MAX_VALUE))
        );
        panelRadius9Layout.setVerticalGroup(
            panelRadius9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRadius9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelRadius2.setBackground(new java.awt.Color(255, 255, 255));
        panelRadius2.setForeground(new java.awt.Color(255, 255, 255));
        panelRadius2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        panelRadius2.setRoundBottomLeft(20);
        panelRadius2.setRoundBottomRight(20);
        panelRadius2.setRoundTopLeft(20);
        panelRadius2.setRoundTopRight(20);

        txt_FullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_FullNameActionPerformed(evt);
            }
        });

        btn_Search.setBackground(new java.awt.Color(153, 255, 0));
        btn_Search.setForeground(new java.awt.Color(255, 255, 255));
        btn_Search.setText("TÌm kiếm");
        btn_Search.setColor(new java.awt.Color(153, 255, 0));
        btn_Search.setColorClick(new java.awt.Color(51, 153, 0));
        btn_Search.setColorOver(new java.awt.Color(0, 204, 51));
        btn_Search.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Search.setRoundBottomLeft(6);
        btn_Search.setRoundBottomRight(6);
        btn_Search.setRoundTopLeft(6);
        btn_Search.setRoundTopRight(6);
        btn_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SearchActionPerformed(evt);
            }
        });

        btn_Add.setBackground(new java.awt.Color(255, 51, 51));
        btn_Add.setForeground(new java.awt.Color(255, 255, 255));
        btn_Add.setColor(new java.awt.Color(255, 51, 51));
        btn_Add.setColorClick(new java.awt.Color(153, 0, 0));
        btn_Add.setColorOver(new java.awt.Color(204, 0, 0));
        btn_Add.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Add.setLabel("Thêm mới");
        btn_Add.setRoundBottomLeft(6);
        btn_Add.setRoundBottomRight(6);
        btn_Add.setRoundTopLeft(6);
        btn_Add.setRoundTopRight(6);
        btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        table.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        table.setSelectionBackground(new java.awt.Color(54, 175, 106));
        jScrollPane3.setViewportView(table);

        txt_City.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CityActionPerformed(evt);
            }
        });

        txt_Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_AddressActionPerformed(evt);
            }
        });

        jLabel8.setText("Họ tên");

        jLabel9.setText("Địa chỉ");

        jLabel10.setText("Thành phố");

        buttonRadius1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reload.png"))); // NOI18N
        buttonRadius1.setColor(new java.awt.Color(224, 224, 224));
        buttonRadius1.setColorClick(new java.awt.Color(153, 153, 153));
        buttonRadius1.setColorOver(new java.awt.Color(204, 204, 204));
        buttonRadius1.setRoundBottomLeft(5);
        buttonRadius1.setRoundBottomRight(5);
        buttonRadius1.setRoundTopLeft(5);
        buttonRadius1.setRoundTopRight(5);
        buttonRadius1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRadius1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRadius2Layout = new javax.swing.GroupLayout(panelRadius2);
        panelRadius2.setLayout(panelRadius2Layout);
        panelRadius2Layout.setHorizontalGroup(
            panelRadius2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRadius2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(panelRadius2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRadius2Layout.createSequentialGroup()
                        .addGroup(panelRadius2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_FullName, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(50, 50, 50)
                        .addGroup(panelRadius2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addGroup(panelRadius2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRadius2Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(128, 128, 128))
                            .addGroup(panelRadius2Layout.createSequentialGroup()
                                .addComponent(txt_City, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btn_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                                .addComponent(buttonRadius1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane3))
                .addGap(40, 40, 40))
        );
        panelRadius2Layout.setVerticalGroup(
            panelRadius2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRadius2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelRadius2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRadius2Layout.createSequentialGroup()
                        .addGroup(panelRadius2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelRadius2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_FullName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelRadius2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGroup(panelRadius2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRadius2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelRadius2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_City, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelRadius2Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(buttonRadius1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRadius9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(panelRadius2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelRadius9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelRadius2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_FullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_FullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FullNameActionPerformed

    private void txt_CityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CityActionPerformed

    private void txt_AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_AddressActionPerformed

    private void btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddActionPerformed
        // TODO add your handling code here:
        d.status=1;
        d.setVisible(true);
    }//GEN-LAST:event_btn_AddActionPerformed

    private void btn_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SearchActionPerformed
        // TODO add your handling code here:
        String str = txt_FullName.getText()+"%"+txt_Address.getText()+"%"+txt_City.getText();
        Object[][] datamodel;
        datamodel = cusBLL.convertList(cusBLL.searchCustomer(str));
        String[] title={"ID","Password","FullName","Address","City","Count Order","Action"};
        DefaultTableModel model = new DefaultTableModel(datamodel,title);
        table.setModel(model);
        ActionTable();
        
    }//GEN-LAST:event_btn_SearchActionPerformed

    private void buttonRadius1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRadius1ActionPerformed
        // TODO add your handling code here:
        loadCustomers();
        txt_FullName.setText("");
        txt_Address.setText("");
        txt_City.setText("");
    }//GEN-LAST:event_buttonRadius1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Custom.ButtonRadius btn_Add;
    private Custom.ButtonRadius btn_Search;
    private Custom.ButtonRadius buttonRadius1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private Custom.PanelRadius panelRadius2;
    private Custom.PanelRadius panelRadius9;
    private Custom.TableCustom1 table;
    private javax.swing.JTextField txt_Address;
    private javax.swing.JTextField txt_City;
    private javax.swing.JTextField txt_FullName;
    // End of variables declaration//GEN-END:variables
}
