/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BLL.OrderBLL;
import BLL.CategoryBLL;
import BLL.OrderDetailBLL;
import BLL.VegetableBLL;
import Custom.chartt.ModelChart;
import POJO.Category;
import POJO.Orders;
import POJO.Vegetable;
import java.awt.Color;
import java.sql.Date;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Admin
 */
public class ThongKeGUI extends javax.swing.JPanel {
    private OrderBLL orderBLL = new OrderBLL();
    private OrderDetailBLL orderDetailBLL = new OrderDetailBLL();
    private CategoryBLL cateBLL = new CategoryBLL();
    private VegetableBLL vegBLL = new VegetableBLL();
    
    private List<Orders> listOrder = new ArrayList<>();
    private List<Vegetable> listVegetable = new ArrayList<>();
    private List<Category> listCategory = new ArrayList<>();
     private Set<Integer> listYear = new TreeSet<>();

    
    
    /**
     * Creates new form ThongKeGUI
     */
    public ThongKeGUI() {
        initComponents();
        chart.addLegend("Income", new Color(245,189,135));
        chart.addLegend("Expense", new Color(135,189,245));
//        chart.addLegend("ICost", new Color(189,135,245));
//        chart.addLegend("ICost", new Color(189,135,245));
//        chart.addData(new ModelChart("January", new double[]{500, 200, 80, 89}));
//        chart.addData(new ModelChart("February", new double[]{1600, 750, 90, 150}));
//        chart.addData(new ModelChart("March", new double[]{200, 350, 460, 900}));
//        chart.addData(new ModelChart("April", new double[]{480, 150, 750, 700}));
//        chart.addData(new ModelChart("May", new double[]{350, 540, 300, 150}));
//        chart.addData(new ModelChart("June", new double[]{190, 280, 81, 200}));
        listOrder = orderBLL.loadOrder();
        listVegetable=vegBLL.loadVegetable();
        listCategory=cateBLL.loadCategory();
        lb_order.setText(listOrder.size()+" Hóa đơn");
        lb_Total.setText(Revenue(listOrder)+"");
        lb_Category.setText(listCategory.size()+" Mặt hàng");
        lb_Vegetable.setText(listVegetable.size()+" Sản phẩm");
        loadYear();
        ThongKeVegetable();
        Growth();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void Growth(){//tinh do tang truong
        long millis = System.currentTimeMillis();
        Date date = new Date(millis);
        int monthNow = Integer.parseInt(date.toString().split("-")[1]);
        int yearNow =  Integer.parseInt(date.toString().split("-")[0]);
        float  totalNow = 0;
        float totalPre=0;
        for(Orders o : listOrder){
            if(Integer.parseInt(o.getDate().toString().split("-")[1])==monthNow && Integer.parseInt(o.getDate().toString().split("-")[0])==yearNow){
                totalNow+=o.getTotal();
            }
            else if(Integer.parseInt(o.getDate().toString().split("-")[1])==monthNow-1 && Integer.parseInt(o.getDate().toString().split("-")[0])==yearNow){
                totalPre+=o.getTotal();
            }
        }
        float growth = totalNow/(Float.parseFloat(lb_Total.getText()))*100;
        
        lb_growth.setText("Tăng: "+growth+"%");
        jLabel16.setText("Tăng: "+(totalNow-totalPre)+"đ");
    }
    public float Revenue(List<Orders> list){ //Tính doanh thu
        float total=0;
        Iterator<Orders> iterator = list.iterator();
        while(iterator.hasNext()){
            total+=iterator.next().getTotal();
        }
        return total;
    }
    public float[] RevenueByTime(List<Orders> list, int[] month, int year){//Tinh doanh thu theo tgian
        float[] total = new float[3];
        for(int i = 0 ; i < total.length ; i++){
            total[i]=0;
            for(Orders o : list){
                if(Integer.parseInt(o.getDate().toString().split("-")[1])==month[i] && Integer.parseInt(o.getDate().toString().split("-")[0])==year){
                    total[i]+=o.getTotal();
                }
            }
        }
        return total;
    }
    
    public Object[] checkMonth(){
        String str = cbb_month.getSelectedItem().toString();
        Object[][] obj = new Object[2][3];
        switch(str){
            case "January - March"->{
                int[] o1 = {1,2,3};
                String[] o2 = {"January","Febuary","March"};
                return new Object[]{o1,o2};
            }
            case "April - June"->{
                 int[] o1 = {4,5,6};
                String[] o2 ={"April","May","June"};
                return new Object[]{o1,o2};
            }
            case "July - September"->{
                 int[] o1 = {7,8,9};
                String[] o2 = {"July","August","September"};
                return new Object[]{o1,o2};
            }
            case "October - December"->{
                 int[] o1 = {10,11,12};
                String[] o2 = {"October","November","December"};
                return new Object[]{o1,o2};
                
            }
        }
        return new Object[][]{{1,2,3},{"January","Febuary","March"}};
    }
    
    public void loadYear(){
        for(Orders o : listOrder){
            int year = Integer.parseInt(o.getDate().toString().split("-")[0]);
            listYear.add(year);
        }
        for(int i : listYear){
            cbb_year.addItem(i+"");
        }
    }
    public void ThongKeVegetable(){
        List list = orderDetailBLL.ThongKeVegetable();
        Object[][] datamodel;
        datamodel = orderDetailBLL.covertListThongKe(list);
         String[] title = {"STT","Vegetable","Amount"};
         DefaultTableModel model = new DefaultTableModel(datamodel,title);
         tb_topVegetable.setModel(model);
    }
    public void setChart(String[] month, float[] total){
        chart.clear();
        for(int i = 0 ; i < month.length; i++){
            chart.addData(new ModelChart(month[i], new double[]{total[i], 2000000}));
        }
        chart.start();
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRadius1 = new Custom.PanelRadius();
        panelRadius5 = new Custom.PanelRadius();
        jLabel7 = new javax.swing.JLabel();
        lb_order = new javax.swing.JLabel();
        lb_Total = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        panelRadius7 = new Custom.PanelRadius();
        jLabel9 = new javax.swing.JLabel();
        lb_Category = new javax.swing.JLabel();
        lb_Vegetable = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        panelRadius8 = new Custom.PanelRadius();
        jLabel10 = new javax.swing.JLabel();
        lb_growth = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        panelRadius3 = new Custom.PanelRadius();
        panelRadius2 = new Custom.PanelRadius();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_topVegetable = new Custom.TableCustom1();
        panelRadius4 = new Custom.PanelRadius();
        panelRadius6 = new Custom.PanelRadius();
        jLabel2 = new javax.swing.JLabel();
        chart = new Custom.chartt.Chart();
        btn_Save2 = new Custom.ButtonRadius();
        cbb_month = new javax.swing.JComboBox<>();
        cbb_year = new javax.swing.JComboBox<>();
        panelRadius9 = new Custom.PanelRadius();
        jLabel8 = new javax.swing.JLabel();

        panelRadius1.setBackground(new java.awt.Color(255, 255, 255));
        panelRadius1.setRoundBottomLeft(20);
        panelRadius1.setRoundBottomRight(20);
        panelRadius1.setRoundTopLeft(20);
        panelRadius1.setRoundTopRight(20);

        panelRadius5.setBackground(new java.awt.Color(127, 192, 214));
        panelRadius5.setInheritsPopupMenu(true);
        panelRadius5.setPreferredSize(new java.awt.Dimension(276, 87));
        panelRadius5.setRoundBottomLeft(20);
        panelRadius5.setRoundBottomRight(20);
        panelRadius5.setRoundTopLeft(20);
        panelRadius5.setRoundTopRight(20);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Doanh số ");

        lb_order.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_order.setForeground(new java.awt.Color(255, 255, 255));
        lb_order.setText("2 Hóa đơn");

        lb_Total.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_Total.setForeground(new java.awt.Color(255, 255, 255));
        lb_Total.setText("450.000 VNĐ");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\NetBeansProjects\\marketHibernate\\src\\main\\java\\icon\\money.png")); // NOI18N

        javax.swing.GroupLayout panelRadius5Layout = new javax.swing.GroupLayout(panelRadius5);
        panelRadius5.setLayout(panelRadius5Layout);
        panelRadius5Layout.setHorizontalGroup(
            panelRadius5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRadius5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelRadius5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_order, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(15, 15, 15))
        );
        panelRadius5Layout.setVerticalGroup(
            panelRadius5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRadius5Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panelRadius5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRadius5Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lb_order, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lb_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7))
        );

        panelRadius7.setBackground(new java.awt.Color(163, 206, 113));
        panelRadius7.setPreferredSize(new java.awt.Dimension(276, 100));
        panelRadius7.setRoundBottomLeft(20);
        panelRadius7.setRoundBottomRight(20);
        panelRadius7.setRoundTopLeft(20);
        panelRadius7.setRoundTopRight(20);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Sản phẩm");

        lb_Category.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_Category.setForeground(new java.awt.Color(255, 255, 255));
        lb_Category.setText("8 Mặt hàng");

        lb_Vegetable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_Vegetable.setForeground(new java.awt.Color(255, 255, 255));
        lb_Vegetable.setText("30 sản phẩm");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\NetBeansProjects\\marketHibernate\\src\\main\\java\\icon\\box.png")); // NOI18N

        javax.swing.GroupLayout panelRadius7Layout = new javax.swing.GroupLayout(panelRadius7);
        panelRadius7.setLayout(panelRadius7Layout);
        panelRadius7Layout.setHorizontalGroup(
            panelRadius7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRadius7Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelRadius7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_Vegetable, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_Category, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addContainerGap())
        );
        panelRadius7Layout.setVerticalGroup(
            panelRadius7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRadius7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(3, 3, 3)
                .addComponent(lb_Category)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_Vegetable, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRadius7Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        panelRadius8.setBackground(new java.awt.Color(245, 195, 59));
        panelRadius8.setRoundBottomLeft(20);
        panelRadius8.setRoundBottomRight(20);
        panelRadius8.setRoundTopLeft(20);
        panelRadius8.setRoundTopRight(20);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Cùng kỳ tháng trước");

        lb_growth.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_growth.setForeground(new java.awt.Color(255, 255, 255));
        lb_growth.setText("Tăng: 100%");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Tăng: 450.000 VNĐ");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\NetBeansProjects\\marketHibernate\\src\\main\\java\\icon\\technique.png")); // NOI18N

        javax.swing.GroupLayout panelRadius8Layout = new javax.swing.GroupLayout(panelRadius8);
        panelRadius8.setLayout(panelRadius8Layout);
        panelRadius8Layout.setHorizontalGroup(
            panelRadius8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRadius8Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelRadius8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(lb_growth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addContainerGap())
        );
        panelRadius8Layout.setVerticalGroup(
            panelRadius8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRadius8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRadius8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelRadius8Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_growth, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16))
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelRadius1Layout = new javax.swing.GroupLayout(panelRadius1);
        panelRadius1.setLayout(panelRadius1Layout);
        panelRadius1Layout.setHorizontalGroup(
            panelRadius1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRadius1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(panelRadius5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(panelRadius7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(panelRadius8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        panelRadius1Layout.setVerticalGroup(
            panelRadius1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRadius1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(panelRadius1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelRadius8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRadius7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRadius5, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );

        panelRadius3.setBackground(new java.awt.Color(255, 255, 255));
        panelRadius3.setRoundBottomLeft(20);
        panelRadius3.setRoundBottomRight(20);
        panelRadius3.setRoundTopLeft(20);
        panelRadius3.setRoundTopRight(20);

        panelRadius2.setBackground(new java.awt.Color(127, 192, 214));
        panelRadius2.setRoundTopLeft(20);
        panelRadius2.setRoundTopRight(20);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Top sản phẩm bán chạy nhất");

        javax.swing.GroupLayout panelRadius2Layout = new javax.swing.GroupLayout(panelRadius2);
        panelRadius2.setLayout(panelRadius2Layout);
        panelRadius2Layout.setHorizontalGroup(
            panelRadius2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRadius2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRadius2Layout.setVerticalGroup(
            panelRadius2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRadius2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        tb_topVegetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane2.setViewportView(tb_topVegetable);

        javax.swing.GroupLayout panelRadius3Layout = new javax.swing.GroupLayout(panelRadius3);
        panelRadius3.setLayout(panelRadius3Layout);
        panelRadius3Layout.setHorizontalGroup(
            panelRadius3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRadius2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRadius3Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        panelRadius3Layout.setVerticalGroup(
            panelRadius3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRadius3Layout.createSequentialGroup()
                .addComponent(panelRadius2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRadius4.setBackground(new java.awt.Color(255, 255, 255));
        panelRadius4.setRoundBottomLeft(20);
        panelRadius4.setRoundBottomRight(20);
        panelRadius4.setRoundTopLeft(20);
        panelRadius4.setRoundTopRight(20);

        panelRadius6.setBackground(new java.awt.Color(127, 192, 214));
        panelRadius6.setRoundTopLeft(20);
        panelRadius6.setRoundTopRight(20);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Doanh thu cửa hàng");

        javax.swing.GroupLayout panelRadius6Layout = new javax.swing.GroupLayout(panelRadius6);
        panelRadius6.setLayout(panelRadius6Layout);
        panelRadius6Layout.setHorizontalGroup(
            panelRadius6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRadius6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRadius6Layout.setVerticalGroup(
            panelRadius6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRadius6Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btn_Save2.setForeground(new java.awt.Color(255, 255, 255));
        btn_Save2.setText("Restart");
        btn_Save2.setColor(new java.awt.Color(0, 204, 204));
        btn_Save2.setColorClick(new java.awt.Color(0, 102, 102));
        btn_Save2.setColorOver(new java.awt.Color(0, 153, 153));
        btn_Save2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Save2.setRoundBottomLeft(6);
        btn_Save2.setRoundBottomRight(6);
        btn_Save2.setRoundTopLeft(6);
        btn_Save2.setRoundTopRight(6);
        btn_Save2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Save2ActionPerformed(evt);
            }
        });

        cbb_month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January - March", "April - June", "July - September", "October - December" }));
        cbb_month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_monthActionPerformed(evt);
            }
        });

        cbb_year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_yearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRadius4Layout = new javax.swing.GroupLayout(panelRadius4);
        panelRadius4.setLayout(panelRadius4Layout);
        panelRadius4Layout.setHorizontalGroup(
            panelRadius4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRadius6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRadius4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelRadius4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chart, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRadius4Layout.createSequentialGroup()
                        .addComponent(cbb_month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbb_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Save2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
        );
        panelRadius4Layout.setVerticalGroup(
            panelRadius4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRadius4Layout.createSequentialGroup()
                .addComponent(panelRadius6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chart, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelRadius4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Save2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbb_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbb_month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        panelRadius9.setBackground(new java.awt.Color(63, 86, 185));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Thống kê");

        javax.swing.GroupLayout panelRadius9Layout = new javax.swing.GroupLayout(panelRadius9);
        panelRadius9.setLayout(panelRadius9Layout);
        panelRadius9Layout.setHorizontalGroup(
            panelRadius9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRadius9Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRadius9Layout.setVerticalGroup(
            panelRadius9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRadius9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRadius9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRadius1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelRadius3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelRadius4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelRadius9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(panelRadius1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelRadius3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRadius4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Save2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Save2ActionPerformed
        // TODO add your handling code here:
        chart.start();

    }//GEN-LAST:event_btn_Save2ActionPerformed

    private void cbb_monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_monthActionPerformed
        int year = Integer.parseInt(cbb_year.getSelectedItem().toString());
        Object[] arr = checkMonth();
        int[] monthInt = (int[])arr[0];
        String[] monthStr = (String[])arr[1];
        float[] total=RevenueByTime(listOrder, monthInt, year);
        setChart(monthStr, total);
    }//GEN-LAST:event_cbb_monthActionPerformed

    private void cbb_yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_yearActionPerformed
        int year = Integer.parseInt(cbb_year.getSelectedItem().toString());
        Object[] arr = checkMonth();
        int[] monthInt = (int[])arr[0];
        String[] monthStr = (String[])arr[1];
        float[] total=RevenueByTime(listOrder, monthInt, year);
        setChart(monthStr, total);
    }//GEN-LAST:event_cbb_yearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Custom.ButtonRadius btn_Save2;
    private javax.swing.JComboBox<String> cbb_month;
    private javax.swing.JComboBox<String> cbb_year;
    public Custom.chartt.Chart chart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb_Category;
    private javax.swing.JLabel lb_Total;
    private javax.swing.JLabel lb_Vegetable;
    private javax.swing.JLabel lb_growth;
    private javax.swing.JLabel lb_order;
    private Custom.PanelRadius panelRadius1;
    private Custom.PanelRadius panelRadius2;
    private Custom.PanelRadius panelRadius3;
    private Custom.PanelRadius panelRadius4;
    private Custom.PanelRadius panelRadius5;
    private Custom.PanelRadius panelRadius6;
    private Custom.PanelRadius panelRadius7;
    private Custom.PanelRadius panelRadius8;
    private Custom.PanelRadius panelRadius9;
    private Custom.TableCustom1 tb_topVegetable;
    // End of variables declaration//GEN-END:variables
}
